travis:
  secure:
    BINSTAR_TOKEN: O+4RTeaP/EY0ns2bt4o9SE7lwf/o+UShZTecVBG2GLNYqRb1q23+kjzg3+RuBojUtipafCk9sXt8qOw/2/Q99RMju6x/6kCqLIohFlynEbXtzBSDWuk1xS2VQObWoeU05BCvFWotKfteAWVSpSuE20aaM6fSz/Zc6RBLPDaIHzaBj02MsRiB9Ssrsb6aA9rrzTop2X+OfNdMEKoky0coQhDXLI7WcTId3ykaY0OAcE/BTqOygWRNyF9+EECGUr5o8iA70HNN3SlsqT5PmgeZUaKpmoH7uGoOOBzJKo18ovpbji18LBNLZh5kA3ygKaceMIBLApVisoWzbvZuOsB3c9zqQMVStt80IBz9H55nub5Eqe460zWjkrbPb7XgviJIl3TZku+13h3yCoviKFdPRUvqB1lbmu7xJlNmoYNZ83d9F7brbw7Nbzc8ZLS0Mi0UzYDS50GAKDJHv20x+OMZpFogEDPK4Nft6XZBZ8a1W8CCtQ7YOIL+Mkv4JLctIw5//OcT9i5XKW5NlIuAf5QOCa9vOnCsTb+Pc2ll/CTuG+29lh4VodwSHkJRv02YhdTDAnUl2T15udnfuVpPSmSQVEO2tNliKxRxQYC5+zzEyW+ni1zz63jsVdm4J/3UGsYaVPBLWKh0Tr56e1n+GhSAv9q9oZmVGuy3C1HXbr/dsY0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
