travis:
  secure:
    BINSTAR_TOKEN: e4+oci49E1xlXBAS/WZmuyI3lPveRcdzOa3FEnj6Qrk1t3MMN3t/+5K9G4fka7W1RDMDMwg1Qt9Pgr6134xbHCbLHwCzDpdYOIyWPfnCfN+KHm7RSU4x4+FgRMtkTeyGbsXcCyh0CRqk+g06Fa2JGuSN93dS3WLdsgosBdDmKFG0sGnyhB2QOrNcftTgvUode6pe4jI9Ohtiyo46K5rz4zLLO8Xg36UBbOErfa6VFQ0dxaYMVWZuLOcPPhBqZf2ApPnB6VXmRRJVpDXtN+ohPfqffxPKCHHGWpWpLUnjDDyGFQ1I1+o401d7qmmk1GvkRxOegRvxoAQVNgKmUz8fzQYw12eF3Y8vLyziVoWG2WJIgS6HvbiErrjBaBDlR6MJZnquVJk6Ulgs9/pfJQtRlpK4DVPP0Zfk4TJNg4wIWAHYvrEQWSkrKgzga1wCFR8qwB/w8iEZkqkjqZr65ilCpj6+e1qD/EGSFBVVow4T/Gp8q6YwJY0GvDAvc5d17e45RNkLTHgs2M6WMP++69hEBxEvikzkmkLBPAOu8pWB6krYtjWyYrRpi80K5H+zIoO1TWwHRbUmyJsxn/MrDvQznQmj65cF8k/f7YRNWlYogweC9JlTDOqsSFCvei1PtOKQtg1BmTQqWcEHcStUIevsAJxk153CiCXIDKtAIoBB3F0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
