travis:
  secure:
    BINSTAR_TOKEN: P0T5kr6ucFM/SNNXvj3uTJ1u1PB0j5biqseOYjWhxl2clDyPAw3Yw00OG0beJYRoIEmh0rOGjLLWeNBEAAnk/3X5sJQAqBoa88BYHbVjl7hXDyUfE1NN6ass4Jy32+qODEWuD0+lmBRTuAogTw9w8NaOU3BnrbIHPksyrqFn/ZLADYNA72i0ipcTVDin/Tz5RqswfvvprkVCxcNy9qxV40fakor+juBZ0Lm7dT6iJuKK4wY4alWCpPJhuVJgYw5SxnPeEY5v5GPIXo+ePJgH+QqkwwNcnSwodQdGFJWUyUATr9ydzNufEsOxXgaAH8n+kTpLj5Sq7zIewqv1XCm1zFIuowb6QsyibMRwxm7UaGfRt4J8YVlsDnfGYVHYQ+T/b2rzuMP0RcnulWMP78W3wqOK+jiV72ddUzmyxWcqLB9judI7D4YHHL+Ul49t8LOChZ748WeOYwRzz4fppFiD2hCeatOOqsLV7vKcUvyi01Ils7jzbojQ/0ZfHBjTfJPk29ek926LtSbGwFZjXH3KK2mRXF/TtRNdEZgFgkR04OUAa+ScKsRoWi31NgX00ysLImFQiBdi8ZcVn4NiLyW0ShJevX3NkX+cT9vLFji/uNXU3iF/AQUL8o9HHWv5vFhzbhVfMgdrQu9roYU706fZ5s3bxZ+07E6siLaniGIUfCc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
